---
title: "PartB_preprocess"
author: "Gibran Makyanie"
date: "21/03/2020"
output: html_document
---

```{r}
rm(list = ls())
library(RSQLite)
library(udpipe)
library(cld3)
library(tm)
library(ggplot2)
library(gridExtra)
library(stm)
library(quanteda)
library(textfeatures)
library(sentimentr)
library(qdap)
library(lubridate)
library(stargazer)
library(readr)
library(dplyr)
library(tidyr)
```


# Codes for pre-processing
Just some code I used you can use as a reference. But you can ignore most, because I'm going to add them in the ETL process

```{r}

# ----- Data Importing
conn <- dbConnect(RSQLite::SQLite(), "dataset/inside_airbnb.db") 


# ----- Select listings
listing_sample <- dbGetQuery(conn, 'SELECT * FROM listing limit 500') %>%
  mutate(lang = detect_language(description)) %>% 
  dplyr::rename(listing_id = id) %>%
  filter(lang == 'en') %>%
  mutate(listing_id = as.character(listing_id)) %>%
  mutate(calendar_last_scraped = as_date(as.integer(calendar_last_scraped))) %>%
  group_by(listing_id) %>%
  mutate(calendar_last_scraped_latest = max(calendar_last_scraped)) %>%
  filter(calendar_last_scraped_latest == calendar_last_scraped) %>%
  select(-calendar_last_scraped_latest) %>%
  filter(number_of_reviews > 10)
  

# ----- Select owners of the listings
host_distinct <- unique(listing_sample$host_id)

host_sample <- dbGetQuery(conn, paste('SELECT host_id, host_name FROM host WHERE host_id IN(', paste(host_distinct, collapse = ","), ')'))  %>% 
  distinct(host_id, host_name)


# ----- Select reviews of the listings
listing_distinct <- listing_sample %>%  distinct(listing_id)

review_sample <- dbGetQuery(conn,paste('SELECT * FROM review WHERE listing_id IN', substring(paste(listing_distinct,collapse = ","),2))) %>%
  dplyr::rename(review_id = id) %>%
  mutate(review_id = as.character(review_id)) %>%
  mutate(lang = detect_language(comments)) %>%
  mutate(date = as_date(date)) %>%
  mutate(listing_id = as.character(listing_id)) %>%
  filter(lang == 'en') 



dbDisconnect(conn)


rm(listing_distinct)
rm(host_distinct)
```


# Codes for pre-processing

Output needed: 
- cleaned comments before inserted to udipipe
- cleaned new_description of listings

```{r}

# ----- Cleaning Function
added_stop_words <- c('amsterdam', 'apartment', 'place', 'house','room', 'stay', 'airbnb','bnb')

clean_corpus <- function(corpus){
  corpus <- tm_map(corpus, removePunctuation)
  corpus <- tm_map(corpus, content_transformer(tolower))
  corpus <- tm_map(corpus, removeWords, words = c(stopwords("en"), added_stop_words))
  corpus <- tm_map(corpus, stripWhitespace)
  corpus <- tm_map(corpus, removeNumbers)
  return(corpus)
}

# ----- Clean comments
x <- VCorpus(VectorSource(review_sample$comments))
x <- clean_corpus(x)
cleaned_comments <- as.data.frame(x) # qdap's function to convert corpus to df
review_sample$cleaned_comments <- cleaned_comments$text

rm(x)
rm(cleaned_comments)


# ----- Clean Listing Description
x <- VCorpus(VectorSource(listing$new_description))
x <- clean_corpus(x)
cleaned_description <- as.data.frame(x) # qdap's function to convert corpus to df
listing$cleaned_description <- cleaned_description$text



```

# # Annotate Reviews (Udipipe)

Output needed: lemmatised comments for "ADV","ADJ","NOUN", "AUX", "PART".

```{r }
# ----- tokennise, lemmatise, and POS tag per listing
ud_model <- udpipe_download_model(language = "english")
ud_model <- udpipe_load_model(ud_model$file_model)
review_annotate <- data.frame(udpipe_annotate(ud_model, x = review_sample$cleaned_comments, doc_id = review_sample$review_id)) 

x <- review_annotate %>%
  filter(upos %in% c("ADV","ADJ","NOUN", "AUX", "PART")) %>% # aux and part to capture negations 'did not'
  dplyr::rename(review_id = doc_id) %>%
  mutate(review_id = as.character(review_id)) %>%
  dplyr::group_by(review_id) %>%
  summarise(lemma_reviews = paste(lemma, collapse = " "))

review_sample <- review_sample %>% left_join(x)
rm(x)
rm(ud_model)
```

